title: Java Game Development
description: Creating a 2D game engine the modern Java way
theme: just-the-docs

url: https://majicktek.github.io/javagamedev/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
